### ISSUE TITLE
Swashbuckle.AspNetCore.JsonMultipartFormDataSupport Exception in 1.10

### ISSUE THREAD

**Issue by robertogaxiola** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#22] opened 2024-10-30 15:11 UTC
In version 1.10 i got this error

![SNAG 2024-10-30 0020](https://github.com/user-attachments/assets/d3f60af7-d041-4f8e-b7e6-abee4d3b05cd)

Failed to generate Operation for action - Sierra_Cloud_Online_Orders_Webapi.Controllers.v1.CategoriesController.GetCategories (Sierra_Cloud_Online_Orders_Webapi). See inner exception

Object reference not set to an instance of an object.

 at Swashbuckle.AspNetCore.JsonMultipartFormDataSupport.Integrations.MultiPartJsonOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<<GenerateOperationAsync>b__21_0>d.MoveNext()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<GenerateOperationAsync>d__19.MoveNext()
   
 
![SNAG 2024-10-30 0021](https://github.com/user-attachments/assets/30287d13-96c5-4c74-b337-b40471543dd5)

downgrading to 1.9, the error goes away

sorry if i cant capture the error, this is only what it shows me on every request

**Comment by Morasiu** [comment] 2024-10-30 16:08
Hmm... I will look into that. Can you share model used in `Sierra_Cloud_Online_Orders_Webapi.Controllers.v1.CategoriesController.GetCategories`?

**Comment by robertogaxiola** [comment] 2024-10-30 16:24
its not only that controller, if i remove that controller, the error goes to another, and another.  in this proyect, i don't use JsonMultipartForm models, but the package and initialization got left from a previous code

i will share this project with you, so you can debug it, on other projects, with version 1.10, don't have any issues, but it uses one or two jsonmultipartform models.

i advise, im a noob, and my code looks like a mess

look for the invitation to the repository

**Comment by Morasiu** [comment] 2024-10-30 19:11
I've got it. I will look into this

**Comment by Morasiu** [comment] 2024-10-31 14:16
Sadly I could not reproduce the issue or run your project. But I have an idea. Can you paste the whole Stack Trace of that exception here?

**Comment by minorityuk** [comment] 2024-11-06 13:12
getting the same error 

The exception is 

System.NullReferenceException: Object reference not set to an instance of an object.
   at Swashbuckle.AspNetCore.JsonMultipartFormDataSupport.Integrations.MultiPartJsonOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<GenerateOperationAsync>b__21_0(OpenApiOperation operation, OperationFilterContext filterContext)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository, Func`3 parametersGenerator, Func`3 bodyGenerator, Func`3 applyFilters)

Then the rest of it is 

Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - API.Controllers.###.###.(API). See inner exception
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Swashbuckle.AspNetCore.JsonMultipartFormDataSupport.Integrations.MultiPartJsonOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<GenerateOperationAsync>b__21_0(OpenApiOperation operation, OperationFilterContext filterContext)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository, Func`3 parametersGenerator, Func`3 bodyGenerator, Func`3 applyFilters)
   --- End of inner exception stack trace ---
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository, Func`3 parametersGenerator, Func`3 bodyGenerator, Func`3 applyFilters)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePathsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository, Func`3 operationsGenerator)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePathsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by Gulcitai** [comment] 2024-11-08 15:55
Hello, Morasiu.

The problem is on the following 49 line of  MultiPartJsonOperationFilter method Apply:
var mediaType = operation.RequestBody.Content.First().Value;

Some operaitons like GET, DELETE might not have a request body. 

Could you please fix the problem?
Your package is so useful :) Thank you

**Comment by Morasiu** [comment] 2024-11-15 08:12
It should be fixed in 1.10.1. (Thanks @cloviscoli). Feel free to reopen the issue or create new if needed.

**Closed by Morasiu** 2024-11-15 08:12 UTC
